all: Lab4

Lab4: Tnode.o BST.o BSTEngine.o
	g++ -std=c++11 Tnode.o BST.o BSTEngine.o -o Lab4

Tnode.o: Tnode.cpp
	g++ -std=c++11 -c Tnode.cpp

BST.o:BST.cpp
	g++ -std=c++11 -c BST.cpp

BSTEngine.o: BSTEngine.cpp
	g++ -std=c++11 -c BSTEngine.cpp
