all: Lab7

Lab7: Tnode.o RBT.o RBTEngine.o
	g++ -std=c++11 Tnode.o RBT.o RBTEngine.o -o Lab7

Tnode.o: Tnode.cpp
	g++ -std=c++11 -c Tnode.cpp

RBT.o:RBT.cpp
	g++ -std=c++11 -c RBT.cpp

RBTEngine.o: RBTEngine.cpp
	g++ -std=c++11 -c RBTEngine.cpp
